# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel)
import sys

class Ui_Calculator(object):

    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(374, 416)
        Calculator.setStyleSheet("background-color: rgb(188, 188, 188);")
        self.pushButton = QtWidgets.QPushButton(Calculator)
        self.pushButton.setGeometry(QtCore.QRect(20, 310, 51, 27))
        self.pushButton.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 15px;\n"
"border: 1px solid black;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Calculator)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 310, 51, 27))
        self.pushButton_2.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Calculator)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 310, 51, 27))
        self.pushButton_3.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Calculator)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 260, 51, 27))
        self.pushButton_4.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Calculator)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 260, 51, 27))
        self.pushButton_5.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Calculator)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 260, 51, 27))
        self.pushButton_6.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(Calculator)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 210, 51, 27))
        self.pushButton_8.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Calculator)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 210, 51, 27))
        self.pushButton_9.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Calculator)
        self.pushButton_10.setGeometry(QtCore.QRect(230, 160, 51, 27))
        self.pushButton_10.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 20px;\n"
"border: 1px solid black;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_14 = QtWidgets.QPushButton(Calculator)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 360, 51, 27))
        self.pushButton_14.setStyleSheet("border: 1px solid black;\n"
"background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Calculator)
        self.pushButton_15.setGeometry(QtCore.QRect(300, 310, 51, 27))
        self.pushButton_15.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 17px;\n"
"border: 1px solid black;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Calculator)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 160, 51, 27))
        self.pushButton_16.setStyleSheet("background-color: red;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: beige;\n"
"font: bold 17px;\n"
"border: 1px solid black;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Calculator)
        self.pushButton_17.setGeometry(QtCore.QRect(160, 160, 51, 27))
        self.pushButton_17.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Calculator)
        self.pushButton_18.setGeometry(QtCore.QRect(300, 210, 51, 27))
        self.pushButton_18.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 17px;\n"
"border: 1px solid black;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Calculator)
        self.plainTextEdit.setGeometry(QtCore.QRect(23, 29, 331, 91))
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"font: 36pt \"Roman\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"border:2px solid black;\n"
"padding: 10px;\n"
"font: 34pt \"Agency FB\";")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_11 = QtWidgets.QPushButton(Calculator)
        self.pushButton_11.setGeometry(QtCore.QRect(160, 210, 51, 27))
        self.pushButton_11.setStyleSheet("background-color: lightblue;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_7 = QtWidgets.QPushButton(Calculator)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 260, 51, 27))
        self.pushButton_7.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 15px;\n"
"border: 1px solid black;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_13 = QtWidgets.QPushButton(Calculator)
        self.pushButton_13.setGeometry(QtCore.QRect(230, 210, 51, 27))
        self.pushButton_13.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_19 = QtWidgets.QPushButton(Calculator)
        self.pushButton_19.setGeometry(QtCore.QRect(230, 360, 51, 27))
        self.pushButton_19.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"border: 1px solid black;\n"
"font: bold 20px;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_12 = QtWidgets.QPushButton(Calculator)
        self.pushButton_12.setGeometry(QtCore.QRect(230, 310, 51, 27))
        self.pushButton_12.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 20px;\n"
"border: 1px solid black;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_20 = QtWidgets.QPushButton(Calculator)
        self.pushButton_20.setGeometry(QtCore.QRect(90, 160, 51, 27))
        self.pushButton_20.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(Calculator)
        self.pushButton_21.setGeometry(QtCore.QRect(300, 160, 51, 27))
        self.pushButton_21.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 18px;\n"
"border: 1px solid black;")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Calculator)
        self.pushButton_22.setGeometry(QtCore.QRect(300, 360, 51, 27))
        self.pushButton_22.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"border: 1px solid black;")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(Calculator)
        self.pushButton_23.setGeometry(QtCore.QRect(300, 260, 51, 27))
        self.pushButton_23.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 13px;\n"
"border-color: beige;\n"
"font: bold 17px;\n"
"border: 1px solid black;")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_25 = QtWidgets.QPushButton(Calculator)
        self.pushButton_25.setGeometry(QtCore.QRect(90, 360, 121, 27))
        self.pushButton_25.setStyleSheet("background-color: grey;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 22px;\n"
"border: 1px solid black;")
        self.pushButton_25.setObjectName("pushButton_25")

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.pushButton.setText(_translate("Calculator", "1"))
        self.pushButton_2.setText(_translate("Calculator", "2"))
        self.pushButton_3.setText(_translate("Calculator", "3"))
        self.pushButton_4.setText(_translate("Calculator", "4"))
        self.pushButton_5.setText(_translate("Calculator", "5"))
        self.pushButton_6.setText(_translate("Calculator", "6"))
        self.pushButton_8.setText(_translate("Calculator", "8"))
        self.pushButton_9.setText(_translate("Calculator", "7"))
        self.pushButton_10.setText(_translate("Calculator", "."))
        self.pushButton_14.setText(_translate("Calculator", "0"))
        self.pushButton_15.setText(_translate("Calculator", "%"))
        self.pushButton_16.setText(_translate("Calculator", "C"))
        self.pushButton_17.setText(_translate("Calculator", ")"))
        self.pushButton_18.setText(_translate("Calculator", "+/-"))
        self.pushButton_11.setText(_translate("Calculator", "9"))
        self.pushButton_7.setText(_translate("Calculator", "X"))
        self.pushButton_13.setText(_translate("Calculator", "/"))
        self.pushButton_19.setText(_translate("Calculator", "+"))
        self.pushButton_12.setText(_translate("Calculator", "-"))
        self.pushButton_20.setText(_translate("Calculator", "("))
        self.pushButton_21.setText(_translate("Calculator", "√"))
        self.pushButton_22.setText(_translate("Calculator", "X!"))
        self.pushButton_23.setText(_translate("Calculator", "^"))
        self.pushButton_25.setText(_translate("Calculator", "="))

        def run(self):
            print('asd')

        self.pushButton_2.clicked.connect(run)

txt = QLabel("0")


app = QtWidgets.QApplication(sys.argv)
Calculator = QtWidgets.QDialog()
ui = Ui_Calculator()
ui.setupUi(Calculator)
Calculator.show()
sys.exit(app.exec_())
